flags: {}
packages:
  - abstract-deque/
  - abstract-deque-tests/
  - atomic-primops/
  - atomic-primops/testing/
  - atomic-primops-foreign/
  - atomic-primops-vector/
  - chaselev-deque/
  - lockfree-queue/
  - mega-deque/
extra-deps:
  - bits-atomic-0.1.3
resolver: lts-12.2
