flags: {}
packages:
  - abstract-deque/
  - abstract-deque-tests/
  - atomic-primops/
  - atomic-primops/testing/
  - atomic-primops-foreign/
  - atomic-primops-vector/
  - chaselev-deque/
  - lockfree-queue/
  - mega-deque/
extra-deps:
- git: https://github.com/wangbj/bits-atomic.git
  commit: 78c8cd2c0bbf77356b3becba64c7f99e6d4e208b

resolver: lts-12.4
