flags: {}
packages:
  - abstract-deque/
  - abstract-deque-tests/
  - atomic-primops/
  - atomic-primops/testing/
  - atomic-primops-foreign/
  - atomic-primops-vector/
  - chaselev-deque/
  - lockfree-queue/
  - mega-deque/
extra-deps:
- git: https://github.com/wangbj/bits-atomic.git
  commit: 5137791165cbacea5f10889f04c95c3957cd098e

resolver: lts-12.4
