

test:
#	cabal-dev install --enable-tests
	cabal install --enable-tests
#	./dist/build/test-abstract-deque/test-abstract-deque -j1 +RTS -N1
	./dist/build/test-abstract-deque/test-abstract-deque -j1 +RTS -N2
	./dist/build/test-abstract-deque/test-abstract-deque -j1 +RTS -N3
	./dist/build/test-abstract-deque/test-abstract-deque -j1 +RTS -N4
	./dist/build/test-abstract-deque/test-abstract-deque -j1 +RTS -N8
	./dist/build/test-abstract-deque/test-abstract-deque -j1 +RTS -N16
